version: 1
services:
  - type: web
    name: my-flask-app  # यहाँ पर अपने ऐप का नाम बदलें
    env: python
    plan: free  # यहाँ पर यदि आप paid plan लेना चाहते हैं, तो "free" को हटा दें
    buildCommand: "pip install requests"
    startCommand: "python main.py"
    autoDeploy: true  # यह सेटिंग ऑटोमेटिक डिप्लॉयमेंट के लिए है
    region: us  # यहाँ पर अपनी पसंद का क्षेत्र चुनें (जैसे "us", "eu", "ap" आदि)
